version: '2'
services:
    zookeeper:
        image: dockter/zookeeper:0.1
        ports:
            - "2181:2181"
            - "2888:2888"
            - "3888:3888"
    kafka:
        image: dockter/kafka:0.1
        ports:
            - "9092:9092"
        environment:
            - ZOOKEEPER_CONNECT=zookeeper:2181
            - TOPIC_LIST=bro
        depends_on:
            - zookeeper
